//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Nullable<int> Amount { get; set; }
        public string BillId { get; set; }
        public string DrinkId { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Drink Drink { get; set; }
    }
}
