//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisionDetail
    {
        public string PermisionDetailId { get; set; }
        public string ActionName { get; set; }
        public string PermisionID { get; set; }
    
        public virtual Permision Permision { get; set; }
    }
}
