//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topping_Resource
    {
        public string ResourceId { get; set; }
        public string ToppingId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
