//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class View01_HoaDonBanTrongNgay
    {
        public string BillId { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string CodeVoucher { get; set; }
        public Nullable<int> Total { get; set; }
        public string Payments { get; set; }
        public string TableId { get; set; }
        public System.DateTime OrderTimeStart { get; set; }
        public Nullable<System.DateTime> OrderTimeEnd { get; set; }
    }
}
